// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA5XHjXn0_74I31a684S_Q64kdWOFrJSc',
    appId: '1:588812015480:web:dca35ae8fd8e03ed75da8d',
    messagingSenderId: '588812015480',
    projectId: 'barber-connect1',
    authDomain: 'barber-connect1.firebaseapp.com',
    storageBucket: 'barber-connect1.firebasestorage.app',
    measurementId: 'G-44VZ8WV7BG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJMiutd-hlSHeT7SQr8_rcTVDVk85uIhY',
    appId: '1:588812015480:android:e8d5f8b4dcb5ba9c75da8d',
    messagingSenderId: '588812015480',
    projectId: 'barber-connect1',
    storageBucket: 'barber-connect1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ5rPi2P6WpLdrNQ0W_LRlmCSswEZ-4Ww',
    appId: '1:588812015480:ios:ec8a663c280f680275da8d',
    messagingSenderId: '588812015480',
    projectId: 'barber-connect1',
    storageBucket: 'barber-connect1.firebasestorage.app',
    iosBundleId: 'com.example.barbado',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ5rPi2P6WpLdrNQ0W_LRlmCSswEZ-4Ww',
    appId: '1:588812015480:ios:ec8a663c280f680275da8d',
    messagingSenderId: '588812015480',
    projectId: 'barber-connect1',
    storageBucket: 'barber-connect1.firebasestorage.app',
    iosBundleId: 'com.example.barbado',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA5XHjXn0_74I31a684S_Q64kdWOFrJSc',
    appId: '1:588812015480:web:a1afa65c7a6e1ec875da8d',
    messagingSenderId: '588812015480',
    projectId: 'barber-connect1',
    authDomain: 'barber-connect1.firebaseapp.com',
    storageBucket: 'barber-connect1.firebasestorage.app',
    measurementId: 'G-N8KJB4PJ8J',
  );
}
